edoddridge/aronnax

MIM.f90, test/output_preservation_test.py
Summary of Fortran code style enforced:
- Indentation of two spaces for all block constructs.
- Four-space indentation of continuation lines (with some exceptions to clarify structure of long algebraic expressions).
- Lines should have no trailing whitespace.
- The last line in the file should have one newline, and no additional blank lines.
- Lines should be < 80 characters wide, but I was not successful in breaking all over-long lines.  The remainder are predominantly line comments that I did not wish to move off their line, not knowing what exactly they referred to.
- Spell language keywords in lower case.
- All subroutines should declare `implicit none`
- (Enforcing this required explicitly declaring the handful of variables that were implicit.)
- Spell block terminators `end do`, …
=> Fortran code style

test/output_preservation_test.py
to asserting smallness of an array-wise relative error.
I chose the particular relative errors to allow the suite to still
pass when I manually change the compilation flag to -Ofast from -Og,
on my system.
This change impacts on the following items:
- Relative to Issue #6, the test suite now tolerates small intentional
changes to the numerics, and even (in a crude way) measures what
those changes are.  However, this is a regression in the sense that
it is now awkward to check that a change that wasn't supposed to
change the numerics indeed does not.
- Relative to Issue #29, I have manually confirmed that optimization
settings are not, in fact, significantly changing the results, on
this set of test examples, at this version of the code.  It would be
nice to automate that confirmation …
=> Change refactor testing from demanding exact identity of outputs

MIM.f90, parameters.in, test/beta_plane_bump/parameters.in, test/beta_plane_bump_red_grav/parameters.in, test/beta_plane_gyre/parameters.in, test/beta_plane_gyre_red_grav/parameters.in, test/f_plane/parameters.in, test/f_plane_red_grav/parameters.in
The model prints a warning if the inconsistency between the summed layer thicknesses and the depth of the domain is above a certain threshold. This pull request adds the functionality for the user to specify the threshold. The default value is set at 1%.
This was discussed in #14 .
=> Thickness consistency

MIM.f90
The unused variables identified by `gfortran -Wall` have been removed.
This pull request closes #18.
=> remove unused variables. Closes #18.

MIM.f90, parameters.in, test/beta_plane_bump/parameters.in, test/beta_plane_bump_red_grav/parameters.in, test/beta_plane_gyre/parameters.in, test/beta_plane_gyre_red_grav/parameters.in, test/f_plane/parameters.in, test/f_plane_red_grav/parameters.in
This pull request removes the fortran code for varying the wind stress magnitude and instead takes a time series of length `nTimeSteps` as an input. If no input file is specified the default is an array filled with ones. 
The `DumpWind` variable has been left in the model since it may be of use when debugging simulations - it could be used to verify that the wind stress magnitude is varying as expected.
This obviates both #8 and #9, and closes #21.
Since the number of time steps is set in `parameters.in` and not in the Fortran source code, the wind stress magnitude array is an allocatable array. Thus it provides something of a recipe for us to follow when we implement #12.
=> Give wind magnitude as an input time series

.travis.yml, test/output_preservation_test.py
Tweak the current test suite so that Travis executes all the mim runs under Valgrind to check for memory consistency.  Fixes #37, specifically the content it has above and beyond #6.
=> Travis valgrind

.gitignore, MIM.f90, Makefile, parameters.in, test/beta_plane_bump/parameters.in, test/beta_plane_bump_red_grav/parameters.in, test/beta_plane_gyre/parameters.in, test/beta_plane_gyre_red_grav/parameters.in, test/f_plane/parameters.in, test/f_plane_red_grav/parameters.in, test/output_preservation_test.py
Convert the nx, ny, and layers variables to inputs (from the GRID namelist, for the time being), and covert all the arrays whose sizes depend on them into allocatable arrays.
Exception: Three of the arrays serve the purpose of accepting layerwise input parameters, and Fortran 95 is not happy with filling allocatable arrays from namelists (for some reason).  Change those to be a fixed large size.
Resolves #12 and resolves #53.
=> Dynamic arrays

.gitignore, MIM.f90, Makefile, benchmarks/profile.py
First-pass profiling.  This PR is a smallish grab-bag of profile-related changes
- Define a Python script for easy profiling in the beta plane bump configuration.
- Annotate SOR_solver with intents so I understand it better.
- Profiler-driven loop nesting order change in `evaluate_dudt`, which seems to be worth a 21% end-to-end speedup in the reduced-gravity configuration.
=> Profiling 1

MIM.f90, README.md
Also a style choice, namely declaring the arguments' properties in the same order as they are passed in.
=> Intent declarations for subroutine arguments

test/output_preservation_test.py
In the test suite, it's more useful to make valgrind produce a failure
exit status if any memory errors are detected.
=> Turns out valgrind defaults to preserving the exit status of the underlying program.

benchmarks/profile.py, test/output_preservation_test.py
This is presumably OS-specific, in that, on the advice of
http://www.bnikolic.co.uk/blog/hpc-howto-measure-flops.html, it uses
`perf stat`, which relies on a Linux API for measuring CPU events.  On
Ubuntu, `perf` can be obtained by installing the `linux-tools-generic`
package.
That weird number 530010 is a hex code for "floating point operation"
for my particular CPU, which I discovered through the somewhat annoying
process of building `perfmon2/libpfm4` from source, per the instructions
on http://askubuntu.com/questions/637144/how-to-install-perfmon2-on-ubuntu,
and then running the resulting `showevtinfo` and `check_events` programs,
as advised in http://www.bnikolic.co.uk/blog/hpc-prof-events.html.
=> Pursuant to Issue #48, hack together basic hardware event counting for MIM runs.

docs/aronnax_model.rst, docs/index.rst
The documentation index should serve as a landing page too, as well as the github repo page.  Ergo, the ad should be there.
=> General doc touchups

.travis.yml, Makefile, README.md
Coveralls made it difficult to measure code coverage for both the Fortran and Python code in a cohesive way. Codecov does it very easily and amalgamates the results automatically.
The code coverage tool assesses only the code that is run by the test suite. The test suite does not currently run any of the Hypre code. This PR successfully implements an automated method to show that deficiency.
=> Fortran code coverage

benchmarks/benchmark.py
Since we're not currently sure that Hypre is doing the right thing (see #123 and #124), it doesn't make sense to publicly benchmark it. This closes #128.
Once we're happy that Hypre is doing what it's meant to, then we can reintroduce publicly benchmarking it.
=> comment out hypre benchmarking

README.md, aronnax.conf, docs/examples.rst, docs/index.rst, docs/installation.rst, docs/running_aronnax.rst
A grad bag of small enhancements for the documentation.
Added units to Coriolis parameter in config file and described wetmask values, closing #58.
Fixed typo in Davis et al. (2014) reproduction, closing #142.
Described debug_level in more detail.
Added installation instructions for building Hypre locally, closing #126.
Tweaked readme to less aspirational, and more realistic.
=> Documentation

.travis.yml, Makefile, aronnax.f90, docs/installation.rst
As discussed in #73, the model would segfault when it tried to place very large arrays on the stack. The workaround introduced in #72 involved using allocate commands to prevent the arrays from being placed on the stack. However, it was still possible, when running simulations with large grids, to exceed the stack limits and have the model segfault. This PR uses the compiler flag `-fno-stack-arrays` to keep arrays off the stack, and removes the allocate commands, thereby simplifying the source code and improving readability. As discussed in #73, doing this does not affect performance.
=> Move all arrays off the stack

aronnax.conf, aronnax.f90, aronnax/driver.py, docs/running_aronnax.rst, test/beta_plane_bump/aronnax.conf, test/beta_plane_bump_red_grav/aronnax.conf, test/output_preservation_test.py
This PR implements a restart feature - given the appropriate checkpoint files and value for `niter0` the model will continue with a simulation.
There is no requirement that parameters, apart from domain size, remain consistent between runs. The restarted simulation takes in parameters in exactly the same way as a normal run - i.e. through the call to `driver.simulate` or the `aronnax.conf` file.
Other small changes:
- the output directory is no longer wiped clean when starting a simulation (since restarting in a directory shouldn't delete data)
- checkpoint files are dumped at the end of every simulation, as discussed in #118 
- the write_output_` subroutines now have to be told which folder to write into (this change wasn't needed in the end, but seems like a better default so I left it)
=> Add restart functionality

Makefile, aronnax.f90
As identified in #168 some runs produced a warning about underflow when they finished. Using a compiler flag to capture these floating point errors caused 7 of the tests to fail.
This PR stops those tests from failing by initialising the output frequencies to zero before the namelists are read. This means that user specified values will over ride the default zeros.
The `-Wuninitialized` flag was alse added to the test compilation as well.
=> Fix underflow error and add more compiler flags to test executable

aronnax.conf, aronnax.f90, aronnax/driver.py, benchmarks/beta_plane_bump/aronnax.conf, benchmarks/beta_plane_bump_red_grav/aronnax.conf, docs/development.rst, examples/n_layer/beta_plane_bump/aronnax.conf, examples/n_layer/beta_plane_gyre/aronnax.conf, examples/reduced_gravity/beta_plane_bump/aronnax.conf, examples/reduced_gravity/beta_plane_gyre/aronnax.conf, reproductions/Davis_et_al_2014/control/aronnax.conf, reproductions/Davis_et_al_2014/control_final_five/aronnax.conf, test/beta_plane_bump/aronnax.conf, test/beta_plane_bump_debug_test/aronnax.conf, test/beta_plane_bump_red_grav/aronnax.conf, test/beta_plane_gyre/aronnax.conf, test/beta_plane_gyre_free_surf/aronnax.conf, test/beta_plane_gyre_red_grav/aronnax.conf, test/f_plane/aronnax.conf, test/f_plane_red_grav/aronnax.conf, test/output_preservation_test.py, test/periodic_BC/aronnax.conf, test/periodic_BC_red_grav/aronnax.conf, test/physics_tests/f_plane_n_layer_init_u/aronnax.conf, test/physics_tests/f_plane_n_layer_wind/aronnax.conf, test/physics_tests/f_plane_red_grav_init_u/aronnax.conf, test/physics_tests/f_plane_red_grav_wind/aronnax.conf, test/relative_wind/aronnax.conf, test/vertical_diffusion/aronnax.conf
This PR implements a naive diffusive mass flux between layers, as discussed in #175. For most simulations the diffusion coefficient, `kv`, will be set to zero.
It also streamlines the names of the diffusive and viscous parameters, closing #176.
The new functionality is tested in two simulations:
- a 1.5 layer simulation in which the simulated layer thickness is compared to an analytical expectation; and
- a 3 layer simulation in which the thickness of the top and bottom layers is compared, to ensure that they grow at the same rate.
=> Add vertical diffusion

aronnax.conf, aronnax.f90, aronnax/driver.py, docs/running_aronnax.rst, test/output_preservation_test.py
This implements an upwind advection scheme in the continuity equation and refactors the `evaluate_dhdt` subroutine. The refactor splits out the two diffusive contributions and the advective contribution into their own subroutines.
There are now two advection schemes available, and the parameter `hAdvScheme` is used to select between them (see additions to documentation). The upwind scheme changes the output, especially in regions with sharp gradients. However, the changes in the `relative_wind` test are small enough to allow both advection schemes to evaluate against the same blessed output, provided the tolerance is relaxed slightly for the upwind scheme.
This PR lays the groundwork for implementing a more sophisticated advection scheme, which will allow outcroppping (see #26). It also …
=> Add an upwind advection scheme

docs/benchmarks.rst
The benchmarking page of the documentation doesn't say how to reproduce the benchmarks, nor does it specify where the benchmarking script is located. This PR rectifies that deficiency, and closes #187.
=> Describe location of benchmarking script

.travis.yml, aronnax/core.py, aronnax/driver.py, docs/installation.rst, test/output_preservation_test.py
Given the impending end of life for Python 2, Aronnax should support Python 3. This was highlighted during the JOSS review process: https://github.com/openjournals/joss-reviews/issues/592#issuecomment-382356615
This PR makes Aronnax compatible with Python 3, and updates the test suite to run under both Python 2.7 and 3.6, thereby closing #186.
=> Python 3 compatibility

Makefile, benchmarks/benchmark.py, benchmarks/profile.py, examples/run_examples.py, reproductions/Davis_et_al_2014/control/aronnax.conf, reproductions/Davis_et_al_2014/control_final_five/aronnax.conf, reproductions/plot_Davis_et_al_2014.py
In #189 I managed to miss the reproduction, example, and benchmarking scripts. Several of these hadn't been updated in quite some time, and the Davis et al. reproduction didn't run because the config file was missing the `RelativeWind` flag.
While making the benchmarking script compatible with Python 3 I found that the addition of the compiler flag to catch underflow errors caused the model to stop. Squaring very small velocities in the computation of the Bernoulli potential lead to underflow warnings, and the flag was turning these warnings into errors. As mentioned in #191 I've just removed that flag.
=> Python3 compatibility for examples and benchmarks

docs/examples.rst, reproductions/Yang_et_al_2016/plotly_3d_surface_aronnax.py
Small fix for the figure in Yang et al. (2016) reproduction - the rtd version of the docs didn't give enough space for the bathymetry colour bar to plot nicely.
=> Hide colour bar for bathymetry

.travis.yml, aronnax/core.py, docs/development.rst, docs/installation.rst, docs/output.rst, examples/run_examples.py, reproductions/Yang_et_al_2016/plot_spin_up.py, reproductions/Yang_et_al_2016/plotly_3d_surface_aronnax.py, reproductions/plot_Davis_et_al_2014.py, test/output_preservation_test.py, test/physics_tests.py, test/read_output_test.py
A grab bag of fixes and new features related to handling model output.
This PR implements a fix for #197 and ensures that the output is presented to users with axes in the order (z,y,x). It also implements a function to lazily load in multiple timestamps of a field. This new function provides some metadata for the array (axis labels and values). The metadata could be expanded, and perhaps even by making the function automatically look for `aronnax-merged.conf` and ingest lots of metadata from there.
Finally, some tests were added for the new functionality which required the addition of some more modules to the Travis install.
=> Output handling

aronnax/core.py, test/read_output_test.py
The function `open_mfdataarray` didn't respect the location of the variables on the grid. This PR introduces a test that can detect that behaviour, and a fix for the problem.
=> Open_mfdatarray bug fix

src/momentum.f90, test/botDrag_test.py, test/bot_drag/aronnax.conf
Fixes #193 by ensuring that bottom drag is applied in all n-layer simulations, even when n=1.
For posterity, the methodology was:
1. Build a test that identified the bug by failing when n=1, but not when n=2
2. Fix the bug.
=> Bugfix: bottom drag

docs/development.rst, src/enforce_thickness.f90, src/model_main.f90
The subroutine to enforce minimum layer thickness is no longer used or tested - it should be removed.
=> Flush unused subroutine

docs/development.rst, src/io.f90, test/output_preservation_test.py
The subroutine for writing checkpoints was using global indices for the local array. The tests didn't catch it because they didn't try restarting from a multicore simulation. New tests have been added that detect this bug, and it has been fixed.
=> Checkpoint bugfix

docs/aronnax_model.rst
I made f and zeta bold.
(\mathbf has no effect on greek letters so I used \boldsymbol)
One remark: why `g^{'}` and not simply `g'`? The prime gets rendered so high up with `^{'}`.
@edoddridge: Note that this PR is to be merged on your `doc-fixes` branch. Also, I only changed lines 63, 66. All other changes below must have to do with how are text editors handle line breaks. (It's been puzzling me long e.g. when interacting with @glwagner; if you have any idea why that happens let me know..)
=> bold on f and zeta since they are  vectors

docs/aronnax_model.rst
@navidcy pointed out a number of issues with chapter 1 of the docs. This PR addresses those.
- Fixes sign error in equation (1.3).
- Defines variables just after the equation they appear in.
- Fixes indicies for reduced gravity definition.
- Divide forcing by reference density.
Closes #213 .
=> Fix minor issues with docs

aronnax/core.py, docs/development.rst, test/read_output_test.py
Fixe the bug identified in #222.
Rename 'time' to 'iter' since it doesn't represent model time, but actually represents iteration number from the main integration loop.
=> Open mfdataarray bigfix

.gitmodules
As described in #228, the repo url for hypre doesn't work. This PR replaces the old url with a new one.
closes #228
=> Update hypre repo url

.github/workflows/testing.yml
Swapping from Travis to GitHub Actions led to no coverage data for Fortran code. This fixes that problem.
=> Add gcov to get fortran code coverage

src/momentum.f90, src/state_deriv.f90, test/botDrag_test.py, test/bot_drag_red_grav_active_lower_layer/aronnax.conf
Add bottom drag to reduced gravity simulations with an active lower layer.
Added code to allow this feature, and a test to make sure it works as expected.
=> Red grav bot drag

.github/workflows/testing.yml
The github actions yaml had the python version pinned to 3.6. This version is no longer available. Pinned version has been removed. If everything passes, then there's no need to pin the version.
=> Flush python 3.6 requirement

src/barotropic_mode.f90, src/enforce_thickness.f90, src/model_main.f90
Previous behavoiur was to rapidly increase horizontal diffusion as layer thickness approached minimum allowed value. This usually worked, but not always. This revision strictly enforces the minimum layer thickness.
=> Enforce minimum layer thickness
